# Generated by Django 6.0.5 on 2026-06-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Sawal ka sahi jawab kyun hai, yahan vistaar se likhein.', null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='time_taken',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
