# Generated by Django 6.0.6 on 2026-08-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.TextField(max_length=900),
        ),
    ]
