# Generated by Django 6.0.6 on 2026-08-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_question_option1_alter_question_option2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=900),
        ),
    ]
